apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuby
spec:
  project: default
  source:
    repoURL: https://github.com/gbremond/kuby.git
    path: .
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
