datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.monitoring:3100
      - name: Mimir
        uid: mimir
        type: prometheus
        access: proxy
        url: http://mimir.monitoring:3100
