apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 5.5.1
      chart: mimir-distributed
      helm:
        valueFiles:
          - $values/monitoring/mimir/values.yaml
    - repoURL: 'https://github.com/gbremond/kuby.git'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
