alertmanager:
  enabled: false
  replicas: 0
compactor:
  enabled: false
  replicas: 0
rollout_operator:
  enabled: false
  replicas: 0

distributor:
  replicas: 1
  resources:
    requests:
      cpu: 20m
ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false
  resources:
    requests:
      cpu: 20m
overrides_exporter:
  replicas: 1
  resources:
    requests:
      cpu: 20m
querier:
  replicas: 1
  resources:
    requests:
      cpu: 20m
query_frontend:
  replicas: 1
  resources:
    requests:
      cpu: 20m
query_scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 20m
ruler:
  replicas: 1
  resources:
    requests:
      cpu: 20m
store_gateway:
  replicas: 1
  zoneAwareReplication:
    enabled: false
  resources:
    requests:
      cpu: 20m
minio:
  resources:
    requests:
      cpu: 20m
