apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-route
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: HostRegexp(`^argo\..+$`)
      kind: Rule
      services:
        - name: argocd-server
          namespace: argocd
          port: 443
          serversTransport: no-verify-tls
    - match: HostRegexp(`^argo\..+$`) && Header(`Content-Type`, `application/grpc`)
      kind: Rule
      services:
        - name: argocd-server
          namespace: argocd
          port: 443
          scheme: h2c
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: no-verify-tls
  namespace: argocd
spec:
  serverName: argocd-server
  insecureSkipVerify: true